import Head from 'next/head'
import { useStore } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import { wrapper } from '../redux'
import '../styles/globals.scss'

function MyApp({ Component, pageProps }) {
  const store = useStore((state) => state)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='app'>
        <PersistGate loading={null} persistor={store.persistor}>
          <Component {...pageProps} />
        </PersistGate>
      </main>
    </>
  )
}

export default wrapper.withRedux(MyApp)
